<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.vdv.de/ojp" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:siri="http://www.siri.org.uk/siri" targetNamespace="http://www.vdv.de/ojp" elementFormDefault="qualified">
	<xs:annotation>
		<xs:documentation>OJP/OJP_Lines.xsd - Request and response definitions for information on lines</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.siri.org.uk/siri" schemaLocation="../siri/xsd/siri_model/siri_all.xsd"/>
	<xs:include schemaLocation="OJP_All.xsd"/>
	<xs:annotation>
		<xs:documentation>=============================== Line Information Service ==========================================</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>=============================== Line Information Response Group ==========================================</xs:documentation>
	</xs:annotation>
	<xs:group name="LineInformationResponseGroup">
		<xs:annotation>
			<xs:documentation>Line Information response group.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="LineResponseContext" type="ResponseContextStructure" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Context to hold line response objects that occur frequently.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="LineResult" type="LineResultStructure" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:group>
	<xs:annotation>
		<xs:documentation>=============================== LineInformation support functions ==========================================</xs:documentation>
	</xs:annotation>
	<xs:complexType name="LineResultStructure">
		<xs:sequence>
			<xs:element name="ErrorCondition" type="OJPErrorStructure" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Problems related to this Line result.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="LineRef" type="siri:LineRefStructure">
				<xs:annotation>
					<xs:documentation>Reference to the LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="siri:PublishedLineName" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name or Number by which the LINE is known to the public.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DirectionRef" type="siri:DirectionRefStructure" minOccurs="0">
				<xs:annotation>
					<xs:documentation>DIRECTION of LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="RouteGeometry" type="LinearShapeStructure" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The LINE's route geometry. A line can have multiple ROUTEs, and each has its own geometry. The first should be the "main" geometry.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AreaGeometry" type="AreaStructure" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The LINE's main area. Used for MOBILITY SERVICES that cover one or more areas. The interconnection between the areas is not calculated (e.g., exclusion zones can't be modelled). Don't mix RouteGeometry and AreaGeometry in a response.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Mode" type="ModeStructure" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>List of transport modes that are supported by this line.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation>=============================== LineInformation support functions ==========================================</xs:documentation>
	</xs:annotation>
	<xs:complexType name="LineStructure">
		<xs:annotation>
			<xs:documentation>The line structure for the context.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="LineRef" type="siri:LineRefStructure">
				<xs:annotation>
					<xs:documentation>Reference to the LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="siri:PublishedLineName" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name or Number by which the LINE is known to the public.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DirectionRef" type="siri:DirectionRefStructure" minOccurs="0">
				<xs:annotation>
					<xs:documentation>DIRECTION of LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Presentation" type="PresentationStructure" minOccurs="0">
				<xs:annotation>
					<xs:documentation>PRESENTATION of a LINE. Based on NeTEx not SIRI.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PresentationStructure">
		<xs:annotation>
			<xs:documentation>Types describing common presentation properties for Display.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Colour" type="ColourValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Default RGB colour value for graphics associated with ENTITY - e.g. for a LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ColourName" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of default colour value for graphics associated with ENTITY.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ColourSystem" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of colour system used for ColourName and TextColourName: for example, 
					- RAL, https://en.wikipedia.org/wiki/RAL_colour_standard;
					- DIN 6164 http://www.dtpstudio.de/atlas/farbsysteme/DIN%206164_bs00_3.htm; 
					- Pantone (be aware that Pantone is proprietary), etc.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BackgroundColour" type="ColourValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Default RGB background colour value for text and graphics associated with ENTITY - e.g. of a LINE.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BackgroundColourName" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of the background colour (in ColourSystem) for text and graphics associated with entity.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TextColour" type="ColourValueType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Default RGB colour value for text associated with ENTITY.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TextColourName" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of default colour value (in ColourSystem) for text associated with ENTITY.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TextFont" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Identifier of font for text.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TextFontName" type="xs:normalizedString" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Name of font for text.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TextLanguage" type="xs:language" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Default language for text.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<!-- infoLinks purposefully omitted for the time being -->
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ColourValueType">
		<xs:annotation>
			<xs:documentation>Type for a Colour Value.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:hexBinary">
			<xs:maxLength value="6"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation>
		<xs:documentation>========================================== Problems ==========================================</xs:documentation>
	</xs:annotation>
	<xs:simpleType name="LineInformationProblemTypeEnumeration">
		<xs:annotation>
			<xs:documentation>Types of problems that may be returned in responses to LINE INFORMATION requests.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="LINEINFORMATION_LINEUNKNOWN">
				<xs:annotation>
					<xs:documentation>The requested LINE is unknown.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="LINEINFORMATION_OTHER">
				<xs:annotation>
					<xs:documentation>A problem has occurred that does not have a specific problem type.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="LineInformationProblemType" type="LineInformationProblemTypeEnumeration" substitutionGroup="ErrorType"/>
</xs:schema>
