# Validate, lint, build and deploy documentation
name: CI

on:
  # Triggers the workflow on push or pull request events for specific branches
  push:
    branches: [ "master", "main", "changes_for_v*" ]
  pull_request:
    branches: [ "master", "main", "changes_for_v*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-and-lint:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event for branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # https://github.com/marketplace/actions/add-commit#working-with-prs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install xmllint and xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils xsltproc

      - name: Validate structure and lint XSD and XML files
        run: ./.github/scripts/validate-and-lint.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9 # https://github.com/marketplace/actions/add-commit
        with:
          default_author: github_actions
          message: 'Fixed linting issues'

      - name: Validate OJP XML examples
        run: ./.github/scripts/validate-examples.sh

      - name: Validate schema structure for generation for documentation tables
        run: ./docs/validate-schema-conventions.sh

      - name: Generate documentation tables (for validation only)
        run: ./docs/generate-tables.sh
